config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  get  'tasks/:id', to: 'tasks#edit'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'members#new'
  resources :members, only: [:index, :show, :new, :create]
  resources :tasks, only: [:create, :edit, :destroy, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :profile, presence: true, length: {maximum:20}
  has_secure_password
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :member
  
  validates :member_id, presence: true
  validates :content, presence: true, length: {maximum:255}
  validates :status, presence: true, length: {maximum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private

  def require_member_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(member)
    @count_tasks = member.tasks.count
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :require_member_logged_in, only: [:index, :show]
  
  def index
    @members = Member.all.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
    @tasks = @member.tasks.order('created_at DESC').page(params[:page])
    counts(@member)
  end

  def new
    @member = Member.new
  end

  def create
     @member = Member.new(member_params)

    if @member.save
      flash[:success] = 'メンバーを登録しました。'
      redirect_to @member
    else
      flash.now[:danger] = 'メンバーの登録に失敗しました。'
      render :new
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :profile, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @member
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:member_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(name, password)
    @member = Member.find_by(name: name)
    if @member && @member.authenticate(password)
      # ログイン成功
      session[:member_id] = @member.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_member_logged_in
  before_action :correct_member , only: [:edit, :update, :destroy] 
 
  def create
    @task = current_member.tasks.build(task_params)
    if @task.save
      flash[:success] = 'タスク が正常に登録されました。'
      redirect_to root_url
    else
      @tasks = current_member.tasks.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'タスク が登録されませんでした。'
      render 'toppages/index'
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      flash[:success] = 'タスク が正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'タスク が更新されませんでした'
      render :edit
    end
  end


  def destroy
    @task.destroy
    flash[:success] = 'タスクは正常に削除されました'
    redirect_back(fallback_location: root_path)
  end

private
def set_task
  @task = Task.find(params[:id])
end
  
def task_params
  params.require(:task).permit(:content, :status)
end

def correct_member
    @task = current_member.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @member = current_member
      @task = current_member.tasks.build    
      @tasks = current_member.tasks.order('created_at DESC').page(params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_url(member, options = { size: 30 })
    gravatar_id = Digest::MD5::hexdigest(member.profile)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def logged_in?
    !!current_member
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div class="alert alert-warning">
    <ul>
      
<% model.errors.full_tasks.each do |task| %>

        <li>
<%= task %>
</li>
      
<% end %>

    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type,task| %>
<div class="alert alert-<%= task_type %>">
     <%= task %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">  <!--  最上部に固定と反転ナビバー -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" date-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TasksList</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Members', members_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_member.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', member_path(current_member) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
          <%= link_to '新規メンバー登録', signup_path %>
          <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
        
      
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Taskslist</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  </head>

  <body>
    <%=render 'layouts/navbar' %> <!--_navbar.htmlなどパーシャルした分 -->
    <div class="container">
    <%= render 'layouts/flash_tasks' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/members/_members.html.erb
<% if members.any? %>
  <ul class="media-list">
    <% members.each do |member| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(member, { size: 50 }) %>" alt="Noimage">
        </div>
        <div class="media-body">
          <div>
            <%= member.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', member_path(member) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate members %>
<% end %>

app/views/members/index.html.erb
<%= render 'members', members: @members %>

app/views/members/new.html.erb
<div class="text-center">
  <h1>新規メンバー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@member) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :profile, '所属' %>
        <%= f.select :profile, [["グループ1", "グループ1"], ["グループ2", "グループ2"], ["グループ3", "グループ3"], ["グループ4", "グループ4"],["グループ5", "グループ5"]], class:'form-control' %>
      </div>
      

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Password(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<div class="row">
  <aside class="col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @member.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@member, { size: 100 }) %>" alt="Noimage">
        <p>所属:<%= @member.profile %> </p>
      
      </div>
    </div>
  </aside>
  <div class="col-xs-4">
    <ul class="nav nav-tabs nav-justified">
      <li class="
        <%= 'active' if current_page?(member_path(@member)) %>
        ">
        <%= link_to member_path(@member) do %>
        TasksList <span class="badge">
        <%= @count_tasks %></span>
        <% end %>
        <%= render 'tasks/tasks', tasks: @tasks %>
      </li>
    </ul>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">

<%= form_for(@task) do |f| %>

<% if task.errors.any? %>

<div class="alert alert-warning">
  <ul>
    <% task.errors.full_messages.each do |task| %>
  <li><%= task %></li>
  <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
<%= f.label :content, 'タスク' %>
<%= f.text_field :content, class:'form-control' %>
</div>

<div class="form-group">
<%= f.label :status, 'ステータス' %>
 <%= f.select :status, [["着手前", "着手前"], ["進行中", "進行中"], ["完了", "完了"], ["回答待ち", "回答待ち"]], class:'form-control' %>
</div>
<%= f.submit  '登録する',class:'btn btn-primary'  %>

<% end %>
 </div>
</div>

app/views/tasks/_tasks.html.erb
<ul class="media-list">
  <% tasks.each do |task| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(task.member, options = { size: 30 }) %>" alt="Noimage">
      </div>
      <div class="media-body">
        <div><%# taskに紐づいているmemberのname　%>
          <%= link_to task.member.name, member_path(task.member) %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
        <div>
          <p><%= task.content %></p>
          <p><%= task.status %></p>
        </div>
        <div>
        <% if current_member == task.member %>
        <%= link_to "Edit", task, muted: :edit, data: { confirm: "編集する" }, class: 'btn btn-primary btn-xs' %>
        <%= link_to "Delete", task, method: :delete, data: { confirm: "消去しますか?" }, class: 'btn btn-danger btn-xs' %>
        <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<div class="row">
<h1>id:<%= @task.id %>のタスク編集ページ</h1>
<%= render 'form', task: @task %>


<%#= f.submit '更新' %>

<%= link_to '一覧に戻る', root_url %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<% if @tasks.any? %>
<table class="table table-hover" >
  <thead>
    <tr>
      <th>id</th><th>タスク</th><th>ステータス</th>
    </tr>
    
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.id,task %></td>
      <td><%= task.content %></td>
      <td><%= task.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div><%= paginate @tasks %></div>
<% end %>
<%= link_to '新規タスクの登録', new_task_path, class: "btn btn-primary"  %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id:<%= @task.id %>のタスク詳細ページ</h1>
<table class="table table-hover">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
   <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する',edit_task_path(@task), class: 'btn btn-info'  %>
<br>
<%= link_to 'このタスクを削除する',@task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class:'btn btn-danger' %>

app/views/toppages/index.html.erb
<% if logged_in? %>
<p>ログイン中メンバー: <%= current_member.name %>さん</p>
  <div class="row">
    <aside class="col-md-4">
      <%= form_for(@task) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
          <%= f.select :status, [["着手前", "着手前"], ["進行中", "進行中"], ["完了", "完了"], ["回答待ち", "回答待ち"]], class:'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-xs-8">
      <%= render 'tasks/tasks', tasks: @tasks %>
    </div>
  </div>

<% else %>


<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the TasksList</h1>
    <%= link_to '新規メンバー登録をする!', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
<% end %>